### ISSUE TITLE
Elements For Mark-up 

### ISSUE THREAD

**Issue by KSD32** [frabbitry/Ulysses#6]
Here are some of the elements that we can use for marking up the Ulysseus text:

- persName
- location / address/ street 
- speaker
- said
- paragraph 
- allusion

**Comment by ebeshero** [comment]
@frabbitry @BMT45 @KSD32 : Suggestions from meeting with some of you today about mapping *Ulysses*:
* Your text structure (paragraphs, spoken passages) should give you a frame of reference for associating people and allusions with places. You probably don't need a complex chain of attributes to connect these if the XML hierarchy shows it to you. (This makes it "XPath-able".) 
* Think about using attributes to distinguish whether places are physically visited or imagined. 
* We can experiment with lots of data extraction--XML to TSV (plain text tab-separated values), and XML to KML, and XML to other things. The XML is giving you a data structure that you can easily query and transform. 
* Let's consider KML in QGIS, since it seems to accept this, and see if QGIS gives you capacity to work with a detailed historic map of Dublin...this will involve some lookup on @frabbitry 's part.

**Comment by frabbitry** [comment]
@KSD32 @BMT45 
I just finished tagging Nestor, and I think that I have a pretty good idea of what I want the schema to look like. I revised the example schema and renamed it (you can find it at \RNC\ulyssesSchema). Let me know if there's anything about it that you'd like to change or aren't sure about, because otherwise I'd like us to associate our XML documents with that schema moving forward. 

If you'll look at the schema, you'll notice that it's fairly basic. There's not a lot of elements or attributes, but I think that the hierarchy is going to be important. 

* ulysses

     * section (with an attribute listing the section name)

     * chapter (just the name of the chapter you're tagging, Telemachus, Nestor, etc.)

     * location (with the name of the location and the lat lon coordinates)
          * paragraph (```<p>```) or said
               * allusion (to authors, literature, or books)
               * reference (miscellaneous references to other things, such as political or historical events)
               * person (a reference to a specific, such as a historical figure)

Essentially, you wrap everything in a root element called ulysses. Next, you name the section and chapter in an empty tag. I want the setting or the place in Dublin where the characters are at (this is something that's going to be mentioned in the annotation) to be tagged and the lat and lon coordinates of that location to be marked as attributes (look that up with [open street maps](https://www.openstreetmap.org)). If there's only one location, wrap everything in one location tag. If the setting changes, then tag each section of the chapter based on where the characters are at. After some careful deliberation, I decided that it's probably going to be best if we tag only the setting right now and not the locations that are referenced because I don't want this to become too complicated mapping-wise. Inside of the location go the paragraphs and the lines of dialogue (indicated by dashes), and inside of those go allusions (usually literary allusions), references (a miscellaneous catch-all element for references that aren't literary in nature), and persons (references to specific people). Information about the allusions and references is going to be in an annotation, and you just have to look at what the annotation is listing as a reference or an allusion, tag that, and then list like the name of the authored being referenced or the name of the historical event. Let me know if you have any questions about this, and we can also go over this at the meeting on Tuesday. 

@ebeshero As for the mapping, I think that historic maps are definitely doable with QGIS. We just have to come up with a suitable skin. Here's a [tutorial](http://fredgibbs.net/tutorials/qgis/overlaying-historic-maps-with-qgis.html) on how to do it. 

Brad, thanks for getting some mark up done on Telemachus. Could you look at the schema and add some tags for locations, allusions/references, and spoken dialogue?
